# Generated by Django 4.2 on 2023-05-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_hobiename_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobie_td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.CharField(max_length=20)),
                ('hobieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobiename_tb')),
            ],
        ),
    ]
