# Generated by Django 4.2 on 2023-05-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_hobie_td'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hobie_td',
            new_name='hobie_tb',
        ),
    ]
