# Generated by Django 4.2 on 2023-05-31 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userhobie_tb'),
        ('siteadmin', '0006_seasonfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasoncountry_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasonfactor_tb')),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.season_tb')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state_tb')),
            ],
        ),
    ]
