# Generated by Django 4.2 on 2023-05-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_register_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='sa',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
