# Generated by Django 4.2 on 2023-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userhobie_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minage', models.IntegerField()),
                ('maxage', models.IntegerField()),
                ('factor', models.CharField(max_length=20)),
            ],
        ),
    ]
