# Generated by Django 4.2 on 2023-06-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_uadmin_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uadmin_tb',
            new_name='message_tb',
        ),
    ]
