# Generated by Django 4.2 on 2023-06-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contact_tb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20)),
                ('contactid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to='user.register_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user.register_tb')),
            ],
        ),
    ]
