# Generated by Django 4.2 on 2023-06-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_seasoncountry_tb'),
        ('user', '0011_blacklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerhobiefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobie_tb')),
                ('hobieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobiename_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
